#ifndef OPEN_WORKSPACE_GLOBAL_HPP
#define OPEN_WORKSPACE_GLOBAL_HPP

#include <QtCore/qglobal.h>

#if defined(OPEN_WORKSPACE_LIBRARY)
#  define OPEN_WORKSPACESHARED_EXPORT Q_DECL_EXPORT
#else
#  define OPEN_WORKSPACESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // OPEN_WORKSPACE_GLOBAL_HPP
