#ifndef SAVE_WORKSPACE_GLOBAL_HPP
#define SAVE_WORKSPACE_GLOBAL_HPP

#include <QtCore/qglobal.h>

#if defined(SAVE_WORKSPACE_LIBRARY)
#  define SAVE_WORKSPACESHARED_EXPORT Q_DECL_EXPORT
#else
#  define SAVE_WORKSPACESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SAVE_WORKSPACE_GLOBAL_HPP
